<table> 
    <thead>
    <tr>
        <th>Id</th>
        <th>FullName</th>
        <th>Email</th>
        <th>Age</th>
        <th>Created</th>
    </tr>
    </thead>
    <tbody>
@foreach($users as $user)
<tr>
    <td>{{$user->id}}</td>
    <td>{{$user->fullname}}</td>
    <td>{{$user->email}}</td>
    <td>{{Carbon\Carbon::parse($user->birthdate)->diffforhumans()}}</td>
    <td>{{Carbon\Carbon::parse($user->Created)->diffforhumans()}}</td>
</tr>
@endforeach
</tbody>
</table>